#!/usr/bin/env python3
"""Generate the embedded terminal mascot from mascot.png (requires Pillow).

Run `make mascot` from the repository root. No image files are needed at runtime.
"""

import json
from pathlib import Path
import subprocess

from PIL import Image, ImageFilter


ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "mascot.png"
OUTPUT = ROOT / "internal/ui/mascot_data.go"


def main():
    image = Image.open(SOURCE).convert("RGBA")
    small = image.resize((64, 64), Image.Resampling.LANCZOS)
    indexed = small.convert("RGB").quantize(colors=32)
    colors = indexed.getpalette()
    palette = ["#%02x%02x%02x" % tuple(colors[i:i + 3]) for i in range(0, 96, 3)]
    rows = [
        "".join(
            " " if small.getpixel((x, y))[3] < 100
            else chr(65 + indexed.getpixel((x, y)))
            for x in range(64)
        )
        for y in range(64)
    ]

    # Each braille cell has two columns and four rows of dots. Trace edges
    # rather than fill areas so the face and lettering work without color.
    source = image.resize((128, 128), Image.Resampling.LANCZOS)
    flat = Image.new("RGB", source.size, "white")
    flat.paste(source, mask=source.getchannel("A"))
    edges = flat.filter(ImageFilter.FIND_EDGES)
    dots = ((0, 0, 1), (0, 1, 2), (0, 2, 4), (1, 0, 8),
            (1, 1, 16), (1, 2, 32), (0, 3, 64), (1, 3, 128))
    mono = []
    for y in range(0, 128, 4):
        line = []
        for x in range(0, 128, 2):
            value = 0
            for dx, dy, bit in dots:
                xx, yy = x + dx, y + dy
                if 0 < xx < 127 and 0 < yy < 127 and max(edges.getpixel((xx, yy))) > 115:
                    value |= bit
            line.append(chr(0x2800 + value) if value else " ")
        mono.append("".join(line).rstrip())

    code = "// Code generated by scripts/generate-mascot.py from mascot.png; DO NOT EDIT.\npackage ui\n\n"
    code += "var finPalette = [...]string{\n"
    code += "".join(json.dumps(color) + ",\n" for color in palette) + "}\n\n"
    code += "var finPixels = [...]string{\n"
    code += "".join(json.dumps(row) + ",\n" for row in rows) + "}\n\n"
    code += "const finMonochrome = `" + "\n".join(mono).strip("\n") + "`\n"
    OUTPUT.write_text(code, encoding="utf-8")
    subprocess.run(["gofmt", "-w", str(OUTPUT)], check=True)


if __name__ == "__main__":
    main()
