// Code generated by scripts/generate-mascot.py from mascot.png; DO NOT EDIT.
package ui

var finPalette = [...]string{
	"#fffdf1",
	"#f9f5e9",
	"#f7f1e4",
	"#f7f0d8",
	"#f4eddf",
	"#dee8e4",
	"#c8c9c3",
	"#a1e1fd",
	"#94d7f7",
	"#8dc7e4",
	"#77c1e7",
	"#72bae1",
	"#6bb3da",
	"#8da1ae",
	"#8d8185",
	"#5da4cc",
	"#5e7f94",
	"#4a94c3",
	"#3f7b9d",
	"#3b6685",
	"#3e4d5f",
	"#244660",
	"#194770",
	"#173856",
	"#0c3c58",
	"#0a2d4d",
	"#221a31",
	"#02080e",
	"#01060a",
	"#000951",
	"#00051b",
	"#000000",
}

var finPixels = [...]string{
	"                                                                ",
	"                                                                ",
	"                     ZVTUZ_                                     ",
	"                     ZPIIJNV_                                   ",
	"                      TMMKIHQZ                                  ",
	"                      VPPLLKHJZ                                 ",
	"                      ZPPMKLMHJZ                                ",
	"                      ZRPPMLLMHN_                               ",
	"                      ZRPRPLMLLHT                               ",
	"                      ZRPRRMPPPKJZ                              ",
	"                      ZRPRRRMJJIJNNQUZ                          ",
	"                      ZPRTQJIJJJJIIHHJQX                        ",
	"                     _XSTLJKLLLKKKKLJHFHQZ                      ",
	"                   _VTXNJKMLLLLKKKKKJHHHHJZ                     ",
	"                  ZPMTJKMMLLLLLLLLKKKKJJMJJX                    ",
	"                _TIMTJLMLKLMLLLLLLLLLKKLUVMJZ                   ",
	"               ZQHMUJLMLLSRLMLLLLLLLLLKKMPSJP^                  ",
	"              ZMHLVJLMMMVVSLMMMMLMLLLKPTTTTVQVZ                 ",
	"             XJHMVMLMMLRRKMMKLMMMMMMKRXQPQTPQ[QT                ",
	"            XJHPZQKPMMLRTTTTTRLMMMMMMXPKQOGQLNZNT               ",
	"           ZJHPZXJMMMMTVSSTTSVTLMLLKSVITONUFQIUTHV              ",
	"          ZMHPXZQLPPLTVMTONNQPXSPTTTVSIVON`QGLQWIIV             ",
	"         _QHMXZVMMMLRZLQNOUUGNRZXWST[SIU[\\\\[GKN_SIJZ            ",
	"         VHKWZYTKPSVZTMNOFO`UGPXTKJHSVHQ][_ZGITZZPHQ_           ",
	"        ZLHSZWZRRXZVZSMN[Q[\\\\NJVPJLMJVSIV_ZTFPVTZWKHV           ",
	"        THMXYWXMTWPKTTLN[[\\__NJXPKIFCFUSMSSJPVMPZZSHMZ          ",
	"       ZJITZXYZPPRPMSVKGX___ZGQWIFFBEANOUQTUQGANZXXLHU          ",
	"       THLXXZZQPRSRMMVSHNYZWQNXGAFOCEEFABGGEABBGZWZSHP_         ",
	"      _PHSZYZPLPSRSMMPUTJNRSQUGAECBBAAEGONACEEANZWYWJIX         ",
	"      XJIWZZPMSMSSRPLFEOUTUTOGAAABEGGOGN[FBCCEBQYWXZPHT         ",
	"      THMZZPMRSRRSPPFDCACFFBEUOOOUU[[[GOOAECCCGXYXXZSHP_        ",
	"     _QHR^TKRRTPSRRJDEEECBBEAN[UOOOOU[[UBCCCEBOZXXYZWIJZ        ",
	"     ^MHTZKMPRTRPRRGDEEECECCEANOGGGGGUUEBCCECGZZYWWYVJHV        ",
	"     ZJIVTPTSRSTSSQNNNGEECCCCEAGOOOOOGBBECEEG[XTQUYYXMHT        ",
	"     XJIVXZZZXWTNJIIHJQGEEECCCEBBFGGEACECEEGUQIIIINVZMHS        ",
	"     VIJVZYXYZQIKKKKJIJQFEEEEEEEECBBCEEEEEGURIKKKKIJVPHQ        ",
	"     VIJVWWWZQIMLLKKKKIPODFDEDDDCCCCCEEFEGURLMLKKKKJJTHQ        ",
	"     VIJWYXZQIMMPPPMLKKKQGGGGGNNNGGGGGGGGVSRPMMMMLLLIQLR        ",
	"     XJIWZZVJMMPRRRRMLKITTTTTTTTTTTTSSTQVWSSRPPPPPPMLMQQ        ",
	"     ZJHTZZQKPRTYZZZWSRSZWWWYYWWWWWYYWWWTTWZZWSRSSSRPMQT        ",
	"     ZLHQZZSRWZZXQQQQQQQUYWYQNUYWWYQOTZWWWXQNUZZZZZZWWRT        ",
	"     _PHPZXZZXYTEAAAAAAAAQZNAAATYYNAAAOZWZNAABUYWYWZUJJX        ",
	"      THJXXWWWXFAEEEEEEEBGZCBEAGZTACECAUYVECEANYWWWZPHPZ        ",
	"      VIHTYWWWUACCCCBBBBANXBCEAG^OAECEBGZXFBEANZWWWXJHS         ",
	"      ZMHMZWWYUACCCEFGGGNXXCCEAG_OAECCEAOZEBEAGZXXZTHJV         ",
	"       SHHUYWZUACEAN[ZZZZZVCCEAG_OAECCCCBUGBEAGZXXZLHPZ         ",
	"       XJHNZXZUBCCBFGGFGUZVECEAG_OAECCCEAGFBEANZXZTHIT          ",
	"       _SIHTZZVCCCCBABCANZUECEAG_OAECCCCCBBCEANZXZJHPZ          ",
	"        XKIJZZXEBCCCCBCANZUECEAG_OAECECCCECCEAOZZQHIT           ",
	"        _SIHNZZGBECCFGGNXZVECEAG_OAEBGGBECCCEBQ_THIR^           ",
	"         ZPIHT_GAEEBUZZZYYVECEAN_OAEBGVFCECECEXXIIKX            ",
	"          XKIHVUAEEBUZWWWYVECEAN_OAECFZQAEEEANZJIIT_            ",
	"          _TIIHVGACAUYWWWYXECEAN^QACANZZGACAGVJIIS_             ",
	"           _SIIJVOGNZWWWWWZOCCGXYZOGNXYYXNGOVMHIRZ              ",
	"            _SIIJQZ_YXXYYWWZUUZZWYZZZZXXYZ_TJIIRZ               ",
	"             _TIIHJTZZXXXXXXZZYXXXWXWXXYZVNHIIRZ                ",
	"              _WLIIHNUZZYXXXXVXXXXXXXZZVQHHIKT^                 ",
	"                XPIIHHLQVZZZZZZZZZZZXTNIHIIPW_                  ",
	"                 ZTMIIHHIJNQTUUUTTQNJHHIILTZ                    ",
	"                   ZTPKIIIHHHHHHHHHHIIKMSZ_                     ",
	"                     ZWSPLKIIIIIIIKLPSWZ_                       ",
	"                       _ZXWTSSSSSTWXZ_                          ",
	"                              _                                 ",
	"                                                                ",
}

const finMonochrome = `                     ⢀⣠⣤⣀⣀
                    ⠰⡇⢴⠶⠤⢬⣉⠓⠦⣄
                     ⢷⠘⡆  ⠈⠙⠲⣌⠓⢄
                     ⢸⡄⣧     ⠈⠳⣄⠳⡄
                     ⢸⡇⣹       ⠸⣦⠹⠤⢤⣄⣀
                     ⢸⠃⡟⣠⠤⢒⣠⠤⠖⠒⠒⠒⠒⠒⠲⠤⢬⣉⠓⢦⣀
                 ⢀⣠⠴⠚⣉⠐⣫⠴⠊⠁         ⠐⠆⣈⣝⠢⣌⠓⢤⡀
               ⣠⠖⢋⣠⡶⢋⡴⠋                ⢰⠒⠒⠷⣄⠱⣄
            ⢀⡴⠊⣡⠖⣩⢊⡴⠋  ⢠⠖⢋⣙⠆         ⢀⡠⠞⠛⢛⡓⠛⠷⡈⡙⢦⡀
           ⡴⠋⡠⢊⡡⠚⢡⠎   ⢀⡧⠞⠛⠒⠒⠲⢤⡀     ⣠⠋⡠⡶⣋⠭⣭⡙⢶⣄⠙⢦⡙⢦⡀
         ⣠⠞⣠⠎⡠⠋⡀⢠⠋  ⢀⡔⢁⣤⠖⣋⣉⣉⡲⢤⡈⢦⡠⠴⠒⠦⡇⢰⢡⡇⠰⡶ ⠹⡌⡞⡇⢰⡙⢦⠙⢆
        ⡴⢃⡼⢡⠞ ⠰⢠⠏⣀⠤⠖⡋⢠⣿⢡⠎⣥⡄⠈⠹⣎⢷⠈⣠⠔⣒⠶⣄⠸⡌⡇⠉  ⡀⣷⢠⡇⠠⠙⢆⠳⡌⢳⡀
       ⡼⢁⠞⣰⠃  ⠆⣾⠊⢀⡤⠴⡆⢸⡇⢸ ⠎   ⢹⢸ ⡟⠈⢀⣀⠼⢦⡙⠾⣄⣀⠴⣣⡧⠚⡠⡇⢱⠈⢣⡘⣆⠱⡄
      ⡼⢁⡎⣰⠃  ⠐⣀⢧⠉⡇⣆ ⢳⡈⢷⡸⡄⢄ ⢀⢆⡾⠋⣰⠥⢺⠙⡆ ⠘⠥⠶⢤⠭⣭⠥⠴⠊⠉⡇⢸  ⢳⠘⡆⢹⡀
     ⢰⠃⡼⢰⠃  ⣠⠞⠁⡸⡄⢧⡘⠄⢀⡱⢤⣉⠛⠒⠞⠒⣋⣤⣚⣁⣀⣀⣉⣤⠤⠔⣒⣩⠁⡼    ⢠⡇⡘   ⢧⠸⡄⢧
     ⡏⢰⠃⡞⠠⢠⠞⠁ ⡇⣧⡘⢦⠁⢠⠎  ⠈⠉⠉⠉⠉⠱⣄⠩⢉⣉⣀⣀⣀⠂ ⡙⢁⡼⠁   ⢀⡞⠠⠁   ⠸⡆⢧⠘⡆
    ⢰⠇⡾⢰⠇⢠⡯⠤⠤⣄⡇⢹⠭⠖⣒⣚⠒⠦⣄      ⠈⠳⣍⡒⠤⠤⠬⠝⣂⠴⠋    ⣠⠋⠐⣂⣒⠂⠄  ⣇⢸⡀⣧
    ⢸ ⡇⢸ ⠈⠐ ⠐⠄⣉⠴⠚⠉⠉⠉⠋⠕⢦⡱⡄       ⠉⠙⠛⠛⠉⠁    ⣠⠞⡡⠖⠋⠉⠉⠉⠓⢤⡁⢻⠈⡇⢸
    ⢸ ⡇⢸ ⠅  ⢡⠞⠁        ⢳⠘⣄⣀⣤⡤⠤⠤⠤⠤⠤⠤⠤⢤⣤⣀⣀⡠⢊⡡⠊        ⠱⡌⢦⡇⢸
    ⢸ ⣇⢸⡄ ⡀⢰⠋⣀⡠⠴⠒⠒⠒⠒⠦⢄⣀⡸ ⠖⠒⢒⡒⠒⣒⠊⠉⠓⢒⡒⠒⣒⠒⠒⠲⠬⢭⣙⠒⠢⢤⣠⠤⠤⠤⣄⣀⢹⠘⡇⣸
    ⠘⡇⢹ ⣇ ⠃⠙⠋⠁⡐⢂⡥⠶⠶⠶⠶⠶⠶⠶⠦⡌⠐⢠⠴⠲⢦⡀⢀⠄⣠⠴⠶⠦⡌⠂ ⠄⣠⠶⠲⢦⡐⣀⠒⠂⠒⠢⢠⡭⢼⠁⡏
     ⢷⠘⡆⢸⡀   ⢨⠁⡟         ⡿ ⡏   ⡇⢸⢰⡇   ⠙⣆⠰ ⡏   ⡇⢸    ⡼⢀⡏⢸⠃
     ⠘⡆⢹⡀⢳   ⠈ ⡇   ⡔⠒⠚⠛⠛⢉⢡ ⡇   ⡇⠘⢸⠃    ⠈⢧⡀⣷   ⡇⠰   ⣰⠃⡼⢀⡏
      ⠹⡄⢳⡀⢳⡀   ⡇   ⠑⠚⠛⠛⠓⡆⢸ ⡇   ⡇ ⢸       ⠣⠌   ⡇   ⡰⠃⡼⢁⡞
       ⠹⡄⠳⡀⠱⡄  ⣧    ⣀⣠⣤⡤⠃⢸ ⡇   ⡇ ⢸   ⢀⢠⡀     ⢠⡇ ⢀⡜⠁⡼⢁⡞
        ⠙⣆⠙⣄⠘⢦⡁⢸⡀  ⢸⡄⠄   ⠠ ⡇   ⡇ ⢸   ⣼ ⠳⡀    ⡼ ⡠⠋⢀⠞⢠⠞
         ⠈⢣⡈⠢⡀⠙⢆⠙⠦⣤⡼⠃⡆    ⡀⢣⣀⣀⣠⠇⠰⠘⠧⣤⠤⠋⠘ ⠙⢤⣤⠤⠚⣠⠞⢀⡴⢃⡴⠃
           ⠙⢦⡈⠢⣀⠙⠲⢄⡐⠈     ⠈  ⠁     ⠂     ⠐⣠⠴⠋⢁⡴⢋⡴⠋
             ⠙⠦⣌⠓⢤⡀⠉⠓⠦⣄⣀             ⢀⣀⡤⠖⠋⢁⡠⠖⣁⡴⠋
               ⠈⠓⠦⣌⠑⠢⢄⣀⠈⠉⠓⠒⠶⠦⠤⠤⠤⠤⠶⠒⠒⠋⠉⣀⣠⠴⠚⣉⡴⠚⠁
                  ⠈⠙⠓⠦⣬⣉⡙⠒⠒⠦⠤⠤⠤⠤⠤⠴⠖⠒⢊⣉⣡⠴⠖⠋⠁
                        ⠉⠉⠛⠒⠒⠒⠒⠒⠒⠒⠛⠉⠉⠁`
